[package]
name = "ovvy-ipc"
version.workspace = true
edition.workspace = true

[dependencies]
ovvy-core = { path = "../core" }
ovvy-window-manager = { path = "../window-manager" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
tokio-tungstenite.workspace = true
futures.workspace = true
