[package]
name = "ovvy-telemetry"
version.workspace = true
edition.workspace = true

[dependencies]
ovvy-core = { path = "../core" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
